### ISSUE TITLE
package android.os does not exist

### ISSUE THREAD

**Issue by MiqueiasDevGames** [open-android/Android#56]
javac -cp /usr/lib/android-sdk/platforms/android-30/android.jar ../com/*.java

**Comment by Yueh-Wang** [comment]
您好，您的邮件我已收到，我会尽快给您回复。

**Comment by developmans** [comment]
已收到！

**Comment by CasterXzs** [comment]
已收到您的邮件，稍后我将浏览，如有疑问，可私聊，谢谢！
